resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

resources:
- name: platform-automation-tasks-azure
  type: azure-blobstore
  source:
    storage_account_name: {{azure_storage_account_name}}
    storage_account_key: {{azure_storage_account_key}}
    container: {{azure_storage_container}}
    versioned_file: platform-automation-tasks-1.0.1-beta.1.zip

- name: platform-automation-image-azure
  type: azure-blobstore
  source:
    storage_account_name: {{azure_storage_account_name}}
    storage_account_key: {{azure_storage_account_key}}
    container: {{azure_storage_container}}
    versioned_file: platform-automation-image-1.0.1-beta.1.tgz
    
jobs:
- name: test-resources
  plan:
  - aggregate:
    - do: 
      - get: platform-automation-tasks-azure
      - get: platform-automation-image-azure
      - config:
            image_resource:
              source:
                repository: pcfnorm/rootfs
                tag: 1.0.28
              type: docker-image
            inputs:
            - name: platform-automation-tasks-azure
            outputs:
            - name: platform-automation-tasks
            platform: linux
            run:
              args:
              - -c
              - unzip platform-automation-tasks-azure/*.zip -d ./platform-automation-tasks
              path: bash
        task: unpack-zip
      - config:
            image_resource:
              source:
                repository: pcfnorm/rootfs
                tag: 1.0.28
              type: docker-image
            inputs:
            - name: platform-automation-image-azure
            outputs:
            - name: platform-automation-image
            platform: linux
            run:
              args:
              - -c
              - tar -xvf platform-automation-image-azure/*.tgz -C ./platform-automation-image
              path: bash
        task: unpack-tarball
  - task: test-resources
    image: platform-automation-image
    file: platform-automation-tasks/tasks/test.yml