---
image_resource:
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.28
  type: docker-image
inputs:
- name: platform-automation-tasks-azure
outputs:
- name: platform-automation-tasks
platform: linux
run:
  args:
  - -c
  - unzip platform-automation-tasks-azure/*.zip -d ./platform-automation-tasks
  path: bash