groups:
- jobs:
  - bootstrap-terraform-state
  - wipe-env
  - create-infrastructure
  name: all
- jobs:
  - create-infrastructure
  name: iaas
jobs:
- name: bootstrap-terraform-state
  plan:
  - do:
    - get: pcf-pipelines-tarball
    - config:
        image_resource:
          source:
            repository: pcfnorm/rootfs
            tag: 1.0.28
          type: docker-image
        inputs:
        - name: pcf-pipelines-tarball
        outputs:
        - name: pcf-pipelines
        platform: linux
        run:
          args:
          - -c
          - tar -xvf pcf-pipelines-tarball/*.tgz
          path: bash
      task: unpack-tarball
  - file: pcf-pipelines/install-pcf/azure/tasks/create-initial-terraform-state/task.yml
    params:
      AZURE_STORAGE_ACCOUNT: {{terraform_azure_storage_account_name}}
      AZURE_STORAGE_KEY: {{terraform_azure_storage_access_key}}
      CONTAINER: {{azure_storage_container_name}}
    task: create-terraform-state
  serial_groups:
  - terraform
- ensure:
    params:
      file: terraform-state-output/terraform.tfstate
    put: terraform-state
  max_in_flight: 1
  name: wipe-env
  plan:
  - aggregate:
    - do:
      - get: pcf-pipelines-tarball
      - config:
          image_resource:
            source:
              repository: pcfnorm/rootfs
              tag: 1.0.28
            type: docker-image
          inputs:
          - name: pcf-pipelines-tarball
          outputs:
          - name: pcf-pipelines
          platform: linux
          run:
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
            path: bash
        task: unpack-tarball
    - get: terraform-state
  - file: pcf-pipelines/install-pcf/azure/tasks/wipe-env/task.yml
    params:
      ARG_WIPE: {{arg_wipe}}
      AZURE_CLIENT_ID: {{azure_client_id}}
      AZURE_CLIENT_SECRET: {{azure_client_secret}}
      AZURE_PCF_TERRAFORM_TEMPLATE: {{azure_pcf_terraform_template}}
      AZURE_REGION: {{azure_region}}
      AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}}
      AZURE_TENANT_ID: {{azure_tenant_id}}
      AZURE_TERRAFORM_PREFIX: {{azure_terraform_prefix}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: wipe-env
  serial: true
  serial_groups:
  - full
- ensure:
    params:
      file: terraform-state-output/terraform.tfstate
    put: terraform-state
  max_in_flight: 1
  name: create-infrastructure
  plan:
    - get: pcf-pipelines
    - get: terraform-state
    - file: pcf-pipelines/install-pcf/azure/tasks/create-infrastructure/task.yml
      params:
        APPS_DOMAIN: {{apps_domain}}
        AZURE_BUILDPACKS_CONTAINER: {{azure_buildpacks_container}}
        AZURE_CLIENT_ID: {{azure_client_id}}
        AZURE_CLIENT_SECRET: {{azure_client_secret}}
        AZURE_DROPLETS_CONTAINER: {{azure_droplets_container}}
        AZURE_MULTI_RESGROUP_NETWORK: {{azure_multi_resgroup_network}}
        AZURE_MULTI_RESGROUP_PCF: {{azure_multi_resgroup_pcf}}
        AZURE_PACKAGES_CONTAINER: {{azure_packages_container}}
        AZURE_PCF_TERRAFORM_TEMPLATE: {{azure_pcf_terraform_template}}
        AZURE_REGION: {{azure_region}}
        AZURE_RESOURCES_CONTAINER: {{azure_resources_container}}
        AZURE_STORAGE_ACCOUNT_NAME: {{azure_storage_account_name}}
        AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}}
        AZURE_TENANT_ID: {{azure_tenant_id}}
        AZURE_TERRAFORM_PREFIX: {{azure_terraform_prefix}}
        AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_CIDR: {{azure_terraform_subnet_dynamic_services_cidr}}
        AZURE_TERRAFORM_SUBNET_ERT_CIDR: {{azure_terraform_subnet_ert_cidr}}
        AZURE_TERRAFORM_SUBNET_INFRA_CIDR: {{azure_terraform_subnet_infra_cidr}}
        AZURE_TERRAFORM_SUBNET_SERVICES1_CIDR: {{azure_terraform_subnet_services1_cidr}}
        AZURE_TERRAFORM_VNET_CIDR: {{azure_terraform_vnet_cidr}}
        AZURE_VM_ADMIN: {{azure_vm_admin}}
        PCF_ERT_DOMAIN: {{pcf_ert_domain}}
        PCF_SSH_KEY_PUB: {{pcf_ssh_key_pub}}
        SYSTEM_DOMAIN: {{system_domain}}
      task: create-infrastructure
  serial: true
  serial_groups:
  - full
resource_types:
- name: azure-blobstore
  source:
    repository: czero/azure-blobstore-resource
  type: docker-image
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
- name: slack-notification
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
  type: docker-image
resources:
- name: terraform-state
  source:
    container: {{azure_storage_container_name}}
    storage_account_key: {{terraform_azure_storage_access_key}}
    storage_account_name: {{terraform_azure_storage_account_name}}
    versioned_file: terraform.tfstate
  type: azure-blobstore
- name: pcf-pipelines-tarball
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.23.11
  type: pivnet
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/miclip/pcf-pipelines-pa
    branch: master
    private_key: ((git_private_key))
    tag_filter: v0.23.11.5